/**
 * ArtQuiz Backend definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpResponse, HttpEvent }  from '@angular/common/http';

import { Observable }                                        from 'rxjs';
import { environment } from 'src/environments/environment';


@Injectable()
export class ConfigurationService {
    public defaultHeaders = new HttpHeaders();

    constructor(protected httpClient: HttpClient) {
    }

    /**
     * 
     * is server alive ?
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public health(observe?: 'body', reportProgress?: boolean): Observable<any>;
    public health(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public health(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public health(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        return this.httpClient.request<any>('get',`${environment.serverBaseURL}/api/health`,
            {
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
